const locationData = [
  { city: "Remote", usaState: "N/A", usaStateID: 53 },
  { city: "Virtual", usaState: "N/A", usaStateID: 53 },
  { city: "Field", usaState: "N/A", usaStateID: 53 },
  { city: "Philadelphia", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Newcastle upon Tyne", country: "United Kingdom", countryID: 220 },
  { city: "Aberdeen Proving Ground", usaState: "Maryland", usaStateID: 21 },
  { city: "Noida", country: "India", countryID: 87 },
  { city: "White Plains", usaState: "New York", usaStateID: 33 },
  { city: "Chicago", usaState: "Illinois", usaStateID: 14 },
  { city: "Murrysville", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Shalimar", usaState: "Florida", usaStateID: 10 },
  { city: "Troy", usaState: "Michigan", usaStateID: 23 },
  { city: "Fort Detrick", usaState: "Maryland", usaStateID: 21 },
  { city: "Lexington", usaState: "Kentucky", usaStateID: 18 },
  { city: "Arlington", usaState: "Virginia", usaStateID: 48 },
  { city: "Palo Alto", usaState: "California", usaStateID: 5 },
  { city: "Urbandale", usaState: "Iowa", usaStateID: 16 },
  { city: "Lackland Air Force Base", usaState: "Texas", usaStateID: 45 },
  { city: "Schriever Air Force Base", usaState: "Colorado", usaStateID: 6 },
  { city: "Camden", usaState: "New Jersey", usaStateID: 31 },
  { city: "Jacksonville", usaState: "Florida", usaStateID: 10 },
  { city: "Fort Meade", usaState: "Maryland", usaStateID: 21 },
  { city: "Kirtland Air Force Base", usaState: "New Mexico", usaStateID: 32 },
  { city: "Rockville", usaState: "Maryland", usaStateID: 21 },
  { city: "Pleasant Hill", usaState: "California", usaStateID: 5 },
  { city: "Shakopee", usaState: "Minnesota", usaStateID: 24 },
  { city: "Richmond", usaState: "Virginia", usaStateID: 48 },
  { city: "Tinker Air Force Base", usaState: "Oklahoma", usaStateID: 37 },
  { city: "Norcross", usaState: "Georgia", usaStateID: 11 },
  { city: "Lubbock", usaState: "Texas", usaStateID: 45 },
  { city: "Charlottesville", usaState: "Virginia", usaStateID: 48 },
  { city: "Andover", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Brentwood", usaState: "Tennessee", usaStateID: 44 },
  { city: "Redstone Arsenal", usaState: "Alabama", usaStateID: 1 },
  { city: "Evansville", usaState: "Indiana", usaStateID: 15 },
  { city: "Wilsonville", usaState: "Oregon", usaStateID: 38 },
  { city: "Eielson Air Force Base", usaState: "Alaska", usaStateID: 2 },
  { city: "Woodlawn", usaState: "Maryland", usaStateID: 21 },
  { city: "Windsor", usaState: "Maryland", usaStateID: 21 },
  { city: "Anchorage", usaState: "Alaska", usaStateID: 2 },
  { city: "Elkridge", usaState: "Maryland", usaStateID: 21 },
  { city: "Silver Spring", usaState: "Maryland", usaStateID: 21 },
  { city: "Windsor Mill", usaState: "Maryland", usaStateID: 21 },
  { city: "Suitland", usaState: "Maryland", usaStateID: 21 },
  { city: "College Park", usaState: "Maryland", usaStateID: 21 },
  { city: "Baltimore", usaState: "Maryland", usaStateID: 21 },
  { city: "Linthicum Heights", usaState: "Maryland", usaStateID: 21 },
  { city: "Germantown", usaState: "Maryland", usaStateID: 21 },
  { city: "Bethesda", usaState: "Maryland", usaStateID: 21 },
  { city: "California", usaState: "Maryland", usaStateID: 21 },
  { city: "Annapolis Junction", usaState: "Maryland", usaStateID: 21 },
  { city: "Beltsville", usaState: "Maryland", usaStateID: 21 },
  { city: "Hagerstown", usaState: "Maryland", usaStateID: 21 },
  { city: "Joint Base Andrews", usaState: "Maryland", usaStateID: 21 },
  { city: "Linthicum", usaState: "Maryland", usaStateID: 21 },
  { city: "Pax River", usaState: "Maryland", usaStateID: 21 },
  { city: "Fort George G. Meade", usaState: "Maryland", usaStateID: 21 },
  { city: "Frederick", usaState: "Maryland", usaStateID: 21 },
  { city: "Lexington Park", usaState: "Maryland", usaStateID: 21 },
  { city: "West Bethesda", usaState: "Maryland", usaStateID: 21 },
  { city: "Columbia", usaState: "Maryland", usaStateID: 21 },
  { city: "Towson", usaState: "Maryland", usaStateID: 21 },
  { city: "Greenbelt", usaState: "Maryland", usaStateID: 21 },
  { city: "Patuxent River", usaState: "Maryland", usaStateID: 21 },
  { city: "Ft Meade", usaState: "Maryland", usaStateID: 21 },
  { city: "Jessup", usaState: "Maryland", usaStateID: 21 },
  { city: "Aberdeen", usaState: "Maryland", usaStateID: 21 },
  { city: "Edgewood", usaState: "Maryland", usaStateID: 21 },
  { city: "Adelphi", usaState: "Maryland", usaStateID: 21 },
  { city: "Gaithersburg", usaState: "Maryland", usaStateID: 21 },
  { city: "Ft Detrick", usaState: "Maryland", usaStateID: 21 },
  { city: "Laurel", usaState: "Maryland", usaStateID: 21 },
  { city: "Clarksburg", usaState: "Maryland", usaStateID: 21 },
  { city: "Carrollton", usaState: "Texas", usaStateID: 45 },
  { city: "Austin", usaState: "Texas", usaStateID: 45 },
  { city: "Waco", usaState: "Texas", usaStateID: 45 },
  { city: "The Woodlands", usaState: "Texas", usaStateID: 45 },
  { city: "College Station", usaState: "Texas", usaStateID: 45 },
  { city: "Belton", usaState: "Texas", usaStateID: 45 },
  { city: "Fort Sam Houston", usaState: "Texas", usaStateID: 45 },
  { city: "Fort Worth", usaState: "Texas", usaStateID: 45 },
  { city: "Ft Worth", usaState: "Texas", usaStateID: 45 },
  { city: "Kingville", usaState: "Texas", usaStateID: 45 },
  { city: "Beaumont", usaState: "Texas", usaStateID: 45 },
  { city: "Bryan", usaState: "Texas", usaStateID: 45 },
  { city: "Coppell", usaState: "Texas", usaStateID: 45 },
  { city: "Big Spring", usaState: "Texas", usaStateID: 45 },
  { city: "Plano", usaState: "Texas", usaStateID: 45 },
  { city: "Temple", usaState: "Texas", usaStateID: 45 },
  { city: "San Antonio", usaState: "Texas", usaStateID: 45 },
  { city: "El Paso", usaState: "Texas", usaStateID: 45 },
  { city: "Ft Sam Houston", usaState: "Texas", usaStateID: 45 },
  { city: "Laredo", usaState: "Texas", usaStateID: 45 },
  { city: "Houston", usaState: "Texas", usaStateID: 45 },
  { city: "Irving", usaState: "Texas", usaStateID: 45 },
  { city: "Denton", usaState: "Texas", usaStateID: 45 },
  { city: "Amarillo", usaState: "Texas", usaStateID: 45 },
  { city: "Richardson", usaState: "Texas", usaStateID: 45 },
  { city: "Vernon", usaState: "Texas", usaStateID: 45 },
  { city: "Southlake", usaState: "Texas", usaStateID: 45 },
  { city: "Lewisville", usaState: "Texas", usaStateID: 45 },
  { city: "Pollok", usaState: "Texas", usaStateID: 45 },
  { city: "Wichita Falls", usaState: "Texas", usaStateID: 45 },
  { city: "Dallas", usaState: "Texas", usaStateID: 45 },
  { city: "DFW Airport", usaState: "Texas", usaStateID: 45 },
  { city: "Tyler", usaState: "Texas", usaStateID: 45 },
  { city: "Port Arthur", usaState: "Texas", usaStateID: 45 },
  { city: "Corpus Christi", usaState: "Texas", usaStateID: 45 },
  { city: "Schaumburg", usaState: "Illinois", usaStateID: 14 },
  { city: "Vernon Hills", usaState: "Illinois", usaStateID: 14 },
  { city: "Lake Zurich", usaState: "Illinois", usaStateID: 14 },
  { city: "Lemont", usaState: "Illinois", usaStateID: 14 },
  { city: "Bolingbrook", usaState: "Illinois", usaStateID: 14 },
  { city: "Rockford", usaState: "Illinois", usaStateID: 14 },
  { city: "Rosemont", usaState: "Illinois", usaStateID: 14 },
  { city: "Peoria", usaState: "Illinois", usaStateID: 14 },
  { city: "Evanston", usaState: "Illinois", usaStateID: 14 },
  { city: "Oakbrook", usaState: "Illinois", usaStateID: 14 },
  { city: "Scott Air Force Base", usaState: "Illinois", usaStateID: 14 },
  { city: "Scott AFB", usaState: "Illinois", usaStateID: 14 },
  { city: "Broadview", usaState: "Illinois", usaStateID: 14 },
  { city: "Oak Brook", usaState: "Illinois", usaStateID: 14 },
  { city: "Mount Prospect", usaState: "Illinois", usaStateID: 14 },
  { city: "Marion", usaState: "Illinois", usaStateID: 14 },
  { city: "Elmhurst", usaState: "Illinois", usaStateID: 14 },
  { city: "Glenview", usaState: "Illinois", usaStateID: 14 },
  { city: "Schiller Park", usaState: "Illinois", usaStateID: 14 },
  { city: "Downers Grove", usaState: "Illinois", usaStateID: 14 },
  { city: "La Salle", usaState: "Illinois", usaStateID: 14 },
  { city: "Naperville", usaState: "Illinois", usaStateID: 14 },
  { city: "Northbrook", usaState: "Illinois", usaStateID: 14 },
  { city: "Wood Dale", usaState: "Illinois", usaStateID: 14 },
  { city: "Alsip", usaState: "Illinois", usaStateID: 14 },
  { city: "Lombard", usaState: "Illinois", usaStateID: 14 },
  { city: "Costa Mesa", usaState: "California", usaStateID: 5 },
  { city: "San Ramon", usaState: "California", usaStateID: 5 },
  { city: "Culver City", usaState: "California", usaStateID: 5 },
  { city: "Carlsbad", usaState: "California", usaStateID: 5 },
  { city: "Menlo Park", usaState: "California", usaStateID: 5 },
  { city: "Pasadena", usaState: "California", usaStateID: 5 },
  { city: "Huntington Beach ", usaState: "California", usaStateID: 5 },
  { city: "Napa", usaState: "California", usaStateID: 5 },
  { city: "San Bernadino", usaState: "California", usaStateID: 5 },
  { city: "Mill Valley", usaState: "California", usaStateID: 5 },
  { city: "Loma Linda", usaState: "California", usaStateID: 5 },
  { city: "Playa Vista", usaState: "California", usaStateID: 5 },
  { city: "Sunnyvale", usaState: "California", usaStateID: 5 },
  { city: "San Francisco", usaState: "California", usaStateID: 5 },
  { city: "Moffett Field", usaState: "California", usaStateID: 5 },
  { city: "Goleta", usaState: "California", usaStateID: 5 },
  { city: "Redwood City", usaState: "California", usaStateID: 5 },
  { city: "La Jolla", usaState: "California", usaStateID: 5 },
  { city: "San Mateo", usaState: "California", usaStateID: 5 },
  { city: "Valencia", usaState: "California", usaStateID: 5 },
  { city: "Santa Ana", usaState: "California", usaStateID: 5 },
  { city: "Bakersfield", usaState: "California", usaStateID: 5 },
  { city: "San Jose", usaState: "California", usaStateID: 5 },
  { city: "Pleasanton", usaState: "California", usaStateID: 5 },
  { city: "Oakland", usaState: "California", usaStateID: 5 },
  { city: "Long Beach", usaState: "California", usaStateID: 5 },
  { city: "Newport Beach", usaState: "California", usaStateID: 5 },
  { city: "Fresno", usaState: "California", usaStateID: 5 },
  { city: "Paso Robles", usaState: "California", usaStateID: 5 },
  { city: "Livermore", usaState: "California", usaStateID: 5 },
  { city: "Buena Park", usaState: "California", usaStateID: 5 },
  { city: "Fremont", usaState: "California", usaStateID: 5 },
  { city: "Santa Clara", usaState: "California", usaStateID: 5 },
  { city: "Edwards", usaState: "California", usaStateID: 5 },
  { city: "Edwards Air Force Base", usaState: "California", usaStateID: 5 },
  { city: "Westlake Village", usaState: "California", usaStateID: 5 },
  { city: "El Segundo", usaState: "California", usaStateID: 5 },
  { city: "Brea", usaState: "California", usaStateID: 5 },
  { city: "Fairfield", usaState: "California", usaStateID: 5 },
  { city: "Irwindale", usaState: "California", usaStateID: 5 },
  { city: "Walnut Creek", usaState: "California", usaStateID: 5 },
  { city: "San Diego", usaState: "California", usaStateID: 5 },
  { city: "Fountain Valley", usaState: "California", usaStateID: 5 },
  { city: "Foster City", usaState: "California", usaStateID: 5 },
  { city: "Modesto", usaState: "California", usaStateID: 5 },
  { city: "San Luis Obispo", usaState: "California", usaStateID: 5 },
  { city: "Highland", usaState: "California", usaStateID: 5 },
  { city: "Irvine", usaState: "California", usaStateID: 5 },
  { city: "Carpinteria", usaState: "California", usaStateID: 5 },
  { city: "Sacramento", usaState: "California", usaStateID: 5 },
  { city: "Chula Vista", usaState: "California", usaStateID: 5 },
  { city: "Mountain View", usaState: "California", usaStateID: 5 },
  { city: "San Leandro", usaState: "California", usaStateID: 5 },
  { city: "Orange County", usaState: "California", usaStateID: 5 },
  { city: "Silicon Valley", usaState: "California", usaStateID: 5 },
  { city: "Los Angeles", usaState: "California", usaStateID: 5 },
  { city: "Burbank", usaState: "California", usaStateID: 5 },
  { city: "Rialto", usaState: "California", usaStateID: 5 },
  { city: "Anaheim", usaState: "California", usaStateID: 5 },
  { city: "Redlands", usaState: "California", usaStateID: 5 },
  { city: "Folsom", usaState: "California", usaStateID: 5 },
  { city: "San Bernardino", usaState: "California", usaStateID: 5 },
  { city: "Inglewood", usaState: "California", usaStateID: 5 },
  { city: "Gardena", usaState: "California", usaStateID: 5 },
  { city: "Malvern", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "King Of Prussia", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Monroeville", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Radnor", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Wayne", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Allentown", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Mechanicsburg", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Newtown Square", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Bryn Mawr", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Pittston", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Dresher", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Horsham", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Plymouth Meeting", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Pittsburgh", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Camp Hill", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Williamsport", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Altoona", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Camp Hill", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Erie", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "East Norriton", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "East Greenville", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Bloomsburg", usaState: "Pennsylvania", usaStateID: 39 },
  { city: "Oldsmar", usaState: "Florida", usaStateID: 10 },
  { city: "Orlando", usaState: "Florida", usaStateID: 10 },
  { city: "Sanford", usaState: "Florida", usaStateID: 10 },
  { city: "West Palm Beach", usaState: "Florida", usaStateID: 10 },
  { city: "Dania Beach", usaState: "Florida", usaStateID: 10 },
  { city: "Gainesville", usaState: "Florida", usaStateID: 10 },
  { city: "Miramar", usaState: "Florida", usaStateID: 10 },
  { city: "Tampa Bay", usaState: "Florida", usaStateID: 10 },
  { city: "Tallahassee", usaState: "Florida", usaStateID: 10 },
  { city: "Boca Raton", usaState: "Florida", usaStateID: 10 },
  { city: "Fort Walton Beach", usaState: "Florida", usaStateID: 10 },
  { city: "Patrick Air Force Base", usaState: "Florida", usaStateID: 10 },
  { city: "Tampa", usaState: "Florida", usaStateID: 10 },
  { city: "Kennedy Space Center", usaState: "Florida", usaStateID: 10 },
  { city: "Eglin Air Force Base", usaState: "Florida", usaStateID: 10 },
  { city: "Miami", usaState: "Florida", usaStateID: 10 },
  { city: "Saint Petersburg", usaState: "Florida", usaStateID: 10 },
  { city: "Fort Lauderdale", usaState: "Florida", usaStateID: 10 },
  { city: "Pensacola", usaState: "Florida", usaStateID: 10 },
  { city: "Ft. Lauderdale", usaState: "Florida", usaStateID: 10 },
  { city: "Fort Walton", usaState: "Florida", usaStateID: 10 },
  { city: "Gainesville", usaState: "Florida", usaStateID: 10 },
  { city: "Bay Pines", usaState: "Florida", usaStateID: 10 },
  { city: "Daytona Beach", usaState: "Florida", usaStateID: 10 },
  { city: "MacDill Air Force Base", usaState: "Florida", usaStateID: 10 },
  { city: "Riverview", usaState: "Florida", usaStateID: 10 },
  { city: "Palm Beach Gardens", usaState: "Florida", usaStateID: 10 },
  { city: "Boynton Beach", usaState: "Florida", usaStateID: 10 },
  { city: "Vergennes", usaState: "Vermont", usaStateID: 47 },
  { city: "White River Junction", usaState: "Vermont", usaStateID: 47 },
  { city: "Ada", usaState: "Michigan", usaStateID: 23 },
  { city: "Traverse City", usaState: "Michigan", usaStateID: 23 },
  { city: "Mt Pleasant", usaState: "Michigan", usaStateID: 23 },
  { city: "Detroit", usaState: "Michigan", usaStateID: 23 },
  { city: "Sterling Heights", usaState: "Michigan", usaStateID: 23 },
  { city: "Saginaw", usaState: "Michigan", usaStateID: 23 },
  { city: "Ann Arbor", usaState: "Michigan", usaStateID: 23 },
  { city: "Livonia", usaState: "Michigan", usaStateID: 23 },
  { city: "Southfield", usaState: "Michigan", usaStateID: 23 },
  { city: "Kalamazoo", usaState: "Michigan", usaStateID: 23 },
  { city: "Plymouth", usaState: "Michigan", usaStateID: 23 },
  { city: "Grand Rapids", usaState: "Michigan", usaStateID: 23 },
  { city: "Battle Creek", usaState: "Michigan", usaStateID: 23 },
  { city: "Warren", usaState: "Michigan", usaStateID: 23 },
  { city: "Farmington Hills", usaState: "Michigan", usaStateID: 23 },
  { city: "Mount Pleasant", usaState: "Michigan", usaStateID: 23 },
  { city: "Houghton", usaState: "Michigan", usaStateID: 23 },
  { city: "Auburn Hills", usaState: "Michigan", usaStateID: 23 },
  { city: "St. Louis", usaState: "Missouri", usaStateID: 26 },
  { city: "St Louis", usaState: "Missouri", usaStateID: 26 },
  { city: "Saint Louis", usaState: "Missouri", usaStateID: 26 },
  { city: "Maryland Heights", usaState: "Missouri", usaStateID: 26 },
  { city: "Kansas City", usaState: "Missouri", usaStateID: 26 },
  { city: "Saint Charles", usaState: "Missouri", usaStateID: 26 },
  { city: "Joplin", usaState: "Missouri", usaStateID: 26 },
  { city: "Branson", usaState: "Missouri", usaStateID: 26 },
  { city: "Jefferson City", usaState: "Missouri", usaStateID: 26 },
  { city: "Arnold", usaState: "New Jersey", usaStateID: 26 },
  { city: "East Orange", usaState: "New Jersey", usaStateID: 26 },
  { city: "Somerset", usaState: "New Jersey", usaStateID: 26 },
  { city: "Belleville", usaState: "New Jersey", usaStateID: 26 },
  { city: "Syosset", usaState: "New Jersey", usaStateID: 26 },
  { city: "Toms River", usaState: "New Jersey", usaStateID: 26 },
  { city: "Livingston", usaState: "New Jersey", usaStateID: 26 },
  { city: "Oceanport", usaState: "New Jersey", usaStateID: 26 },
  { city: "Marlton", usaState: "New Jersey", usaStateID: 26 },
  { city: "Clark", usaState: "New Jersey", usaStateID: 31 },
  { city: "Newark", usaState: "New Jersey", usaStateID: 31 },
  { city: "Paramus", usaState: "New Jersey", usaStateID: 31 },
  { city: "Berkeley Heights", usaState: "New Jersey", usaStateID: 31 },
  { city: "Basking Ridge", usaState: "New Jersey", usaStateID: 31 },
  { city: "Mount Olive", usaState: "New Jersey", usaStateID: 31 },
  { city: "Secaucus", usaState: "New Jersey", usaStateID: 31 },
  { city: "Union", usaState: "New Jersey", usaStateID: 31 },
  { city: "Ewing", usaState: "New Jersey", usaStateID: 31 },
  { city: "Little Falls", usaState: "New Jersey", usaStateID: 31 },
  { city: "Morristown", usaState: "New Jersey", usaStateID: 31 },
  { city: "Parsippany", usaState: "New Jersey", usaStateID: 31 },
  { city: "Hoboken", usaState: "New Jersey", usaStateID: 31 },
  { city: "East Brunswick", usaState: "New Jersey", usaStateID: 31 },
  { city: "New Brunswick", usaState: "New Jersey", usaStateID: 31 },
  { city: "Hackettstown", usaState: "New Jersey", usaStateID: 31 },
  { city: "Jersey City", usaState: "New Jersey", usaStateID: 31 },
  { city: "Moorestown", usaState: "New Jersey", usaStateID: 31 },
  { city: "Monmouth Junction", usaState: "New Jersey", usaStateID: 31 },
  { city: "Trenton", usaState: "New Jersey", usaStateID: 31 },
  { city: "Mountain Lakes", usaState: "New Jersey", usaStateID: 31 },
  { city: "Florham Park", usaState: "New Jersey", usaStateID: 31 },
  { city: "Princeton", usaState: "New Jersey", usaStateID: 31 },
  { city: "Browns Mills", usaState: "New Jersey", usaStateID: 31 },
  { city: "Red Bank", usaState: "New Jersey", usaStateID: 31 },
  { city: "Alexandria", usaState: "Virginia", usaStateID: 48 },
  { city: "McLean", usaState: "Virginia", usaStateID: 48 },
  { city: "Mclean", usaState: "Virginia", usaStateID: 48 },
  { city: "Vienna", usaState: "Virginia", usaStateID: 48 },
  { city: "Fredericksburg", usaState: "Virginia", usaStateID: 48 },
  { city: "Rosslyn", usaState: "Virginia", usaStateID: 48 },
  { city: "Annandale", usaState: "Virginia", usaStateID: 48 },
  { city: "Salem", usaState: "Virginia", usaStateID: 48 },
  { city: "Martinsville", usaState: "Virginia", usaStateID: 48 },
  { city: "Chantilly", usaState: "Virginia", usaStateID: 48 },
  { city: "Chesapeake", usaState: "Virginia", usaStateID: 48 },
  { city: "Ft. Belvoir", usaState: "Virginia", usaStateID: 48 },
  { city: "Suffolk", usaState: "Virginia", usaStateID: 48 },
  { city: "Glen Allen", usaState: "Virginia", usaStateID: 48 },
  { city: "Virginia Beach", usaState: "Virginia", usaStateID: 48 },
  { city: "Crystal City", usaState: "Virginia", usaStateID: 48 },
  { city: "Martinsburg", usaState: "West Virginia", usaStateID: 50 },
  { city: "Newington", usaState: "Virginia", usaStateID: 48 },
  { city: "Hampton", usaState: "Virginia", usaStateID: 48 },
  { city: "Stafford", usaState: "Virginia", usaStateID: 48 },
  { city: "Falls Church", usaState: "Virginia", usaStateID: 48 },
  { city: "Springfield", usaState: "Virginia", usaStateID: 48 },
  { city: "Quantico", usaState: "Virginia", usaStateID: 48 },
  { city: "Harrisonburg", usaState: "Virginia", usaStateID: 48 },
  { city: "McLean Campus", usaState: "Virginia", usaStateID: 48 },
  { city: "Norfolk", usaState: "Virginia", usaStateID: 48 },
  { city: "Herndon", usaState: "Virginia", usaStateID: 48 },
  { city: "Portsmouth", usaState: "Virginia", usaStateID: 48 },
  { city: "Ft Belvoir", usaState: "Virginia", usaStateID: 48 },
  { city: "Fairfax", usaState: "Virginia", usaStateID: 48 },
  { city: "Langley Air Force Base", usaState: "Virginia", usaStateID: 48 },
  { city: "Dahlgren", usaState: "Virginia", usaStateID: 48 },
  { city: "Newport News", usaState: "Virginia", usaStateID: 48 },
  { city: "Fort Belvoir", usaState: "Virginia", usaStateID: 48 },
  { city: "Reston", usaState: "Virginia", usaStateID: 48 },
  { city: "Roanoke", usaState: "Virginia", usaStateID: 48 },
  { city: "Westfields", usaState: "Virginia", usaStateID: 48 },
  { city: "Grand Forks", usaState: "North Dakota", usaStateID: 35 },
  { city: "Bedford Campus", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Waltham", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Stow", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Bedford", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Burlington", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Lynnfield", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Danvers", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Norwood", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Dedham", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Cambridge", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Westwood", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Needham", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Concord", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Billerica", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Boston", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Worcester", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Hanscom Air Force Base", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Pittsfield", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Westford", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Watertown", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Newton", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Framingham", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Natick", usaState: "Massachusetts", usaStateID: 22 },
  { city: "Wright-Patterson Air Force Base", usaState: "Ohio", usaStateID: 36 },
  { city: "Highland Heights", usaState: "Ohio", usaStateID: 36 },
  { city: "Westlake", usaState: "Ohio", usaStateID: 36 },
  { city: "Canton", usaState: "Ohio", usaStateID: 36 },
  { city: "Columbus", usaState: "Ohio", usaStateID: 36 },
  { city: "Dayton", usaState: "Ohio", usaStateID: 36 },
  { city: "Cleveland", usaState: "Ohio", usaStateID: 36 },
  { city: "Cincinnati", usaState: "Ohio", usaStateID: 36 },
  { city: "Mentor", usaState: "Ohio", usaStateID: 36 },
  { city: "Independence", usaState: "Ohio", usaStateID: 36 },
  { city: "Oberlin", usaState: "Ohio", usaStateID: 36 },
  { city: "Albuquerque", usaState: "New Mexico", usaStateID: 32 },
  { city: "Los Alamos", usaState: "New Mexico", usaStateID: 32 },
  { city: "Las Cruces", usaState: "New Mexico", usaStateID: 32 },
  { city: "Shiprock", usaState: "New Mexico", usaStateID: 32 },
  { city: "Mescalero", usaState: "New Mexico", usaStateID: 32 },
  { city: "Santa Fe", usaState: "New Mexico", usaStateID: 32 },
  { city: "White Sands", usaState: "New Mexico", usaStateID: 32 },
  { city: "Fort Huachuca", usaState: "Arizona", usaStateID: 3 },
  { city: "Sierra Vista", usaState: "Arizona", usaStateID: 3 },
  { city: "Inscription House", usaState: "Arizona", usaStateID: 3 },
  { city: "Kayenta", usaState: "Arizona", usaStateID: 3 },
  { city: "Scottsdale", usaState: "Arizona", usaStateID: 3 },
  { city: "Phoenix", usaState: "Arizona", usaStateID: 3 },
  { city: "Ft Huachuca", usaState: "Arizona", usaStateID: 3 },
  { city: "Tucson", usaState: "Arizona", usaStateID: 3 },
  { city: "Glendale", usaState: "Arizona", usaStateID: 3 },
  { city: "Chandler", usaState: "Arizona", usaStateID: 3 },
  { city: "Parker", usaState: "Arizona", usaStateID: 3 },
  { city: "Tempe", usaState: "Arizona", usaStateID: 3 },
  { city: "Beaverton", usaState: "Oregon", usaStateID: 38 },
  { city: "Portland", usaState: "Oregon", usaStateID: 38 },
  { city: "Eugene", usaState: "Oregon", usaStateID: 38 },
  { city: "Roseburg", usaState: "Oregon", usaStateID: 38 },
  { city: "Clackamas", usaState: "Oregon", usaStateID: 38 },
  { city: "Atlanta", usaState: "Georgia", usaStateID: 11 },
  { city: "Decatur", usaState: "Georgia", usaStateID: 11 },
  { city: "Athens", usaState: "Georgia", usaStateID: 11 },
  { city: "Suwanee", usaState: "Georgia", usaStateID: 11 },
  { city: "Duluth", usaState: "Georgia", usaStateID: 11 },
  { city: "Savannah", usaState: "Georgia", usaStateID: 11 },
  { city: "Alpharetta", usaState: "Georgia", usaStateID: 11 },
  { city: "Macon", usaState: "Georgia", usaStateID: 11 },
  { city: "Robins Air Force Base", usaState: "Georgia", usaStateID: 11 },
  { city: "Marietta", usaState: "Georgia", usaStateID: 11 },
  { city: "Fort Gordon", usaState: "Georgia", usaStateID: 11 },
  { city: "Augusta", usaState: "Georgia", usaStateID: 11 },
  { city: "Seattle", usaState: "Washington", usaStateID: 49 },
  { city: "Bellevue", usaState: "Washington", usaStateID: 49 },
  { city: "Everett", usaState: "Washington", usaStateID: 49 },
  { city: "Richland", usaState: "Washington", usaStateID: 49 },
  { city: "Bothell", usaState: "Washington", usaStateID: 49 },
  { city: "Spokane", usaState: "Washington", usaStateID: 49 },
  { city: "Tacoma", usaState: "Washington", usaStateID: 49 },
  { city: "Mountlake Terrace", usaState: "Washington", usaStateID: 49 },
  { city: "Washington", usaState: "District of Columbia", usaStateID: 9 },
  { city: "Bolling Air Force Base", usaState: "District of Columbia", usaStateID: 9 },
  { city: "Wilmington", usaState: "Delaware", usaStateID: 8 },
  { city: "Nashville", usaState: "Tennessee", usaStateID: 44 },
  { city: "Knoxville", usaState: "Tennessee", usaStateID: 44 },
  { city: "Franklin", usaState: "Tennessee", usaStateID: 44 },
  { city: "Oak Ridge", usaState: "Tennessee", usaStateID: 44 },
  { city: "Johnson City", usaState: "Tennessee", usaStateID: 44 },
  { city: "Memphis", usaState: "Tennessee", usaStateID: 44 },
  { city: "Chattanooga", usaState: "Tennessee", usaStateID: 44 },
  { city: "Research Triangle Park", usaState: "North Carolina", usaStateID: 34 },
  { city: "Ft Bragg", usaState: "North Carolina", usaStateID: 34 },
  { city: "Winston-Salem", usaState: "North Carolina", usaStateID: 34 },
  { city: "Charlotte", usaState: "North Carolina", usaStateID: 34 },
  { city: "Durham", usaState: "North Carolina", usaStateID: 34 },
  { city: "Morrisville", usaState: "North Carolina", usaStateID: 34 },
  { city: "Rocky Mount", usaState: "North Carolina", usaStateID: 34 },
  { city: "Raleigh", usaState: "North Carolina", usaStateID: 34 },
  { city: "Salisbury", usaState: "North Carolina", usaStateID: 34 },
  { city: "Asheville", usaState: "North Carolina", usaStateID: 34 },
  { city: "Greenville", usaState: "North Carolina", usaStateID: 34 },
  { city: "Greensboro", usaState: "North Carolina", usaStateID: 34 },
  { city: "Huntersville", usaState: "North Carolina", usaStateID: 34 },
  { city: "Missoula", usaState: "Montana", usaStateID: 27 },
  { city: "Helena", usaState: "Montana", usaStateID: 27 },
  { city: "Saint Cloud", usaState: "Minnesota", usaStateID: 24 },
  { city: "Cass Lake", usaState: "Minnesota", usaStateID: 24 },
  { city: "Burnsville", usaState: "Minnesota", usaStateID: 24 },
  { city: "Marshall", usaState: "Minnesota", usaStateID: 24 },
  { city: "Bloomington", usaState: "Minnesota", usaStateID: 24 },
  { city: "Minneapolis", usaState: "Minnesota", usaStateID: 24 },
  { city: "Lakeville", usaState: "Minnesota", usaStateID: 24 },
  { city: "Mendota Heights", usaState: "Minnesota", usaStateID: 24 },
  { city: "Eden Prairie", usaState: "Minnesota", usaStateID: 24 },
  { city: "Maplewood", usaState: "Minnesota", usaStateID: 24 },
  { city: "Melville", usaState: "New York", usaStateID: 33 },
  { city: "St Paul", usaState: "Minnesota", usaStateID: 24 },
  { city: "Buffalo", usaState: "New York", usaStateID: 33 },
  { city: "Rochester", usaState: "New York", usaStateID: 33 },
  { city: "Syracuse", usaState: "New York", usaStateID: 33 },
  { city: "Farmingdale", usaState: "New York", usaStateID: 33 },
  { city: "Garden City", usaState: "New York", usaStateID: 33 },
  { city: "New York", usaState: "New York", usaStateID: 33 },
  { city: "Long Island", usaState: "New York", usaStateID: 33 },
  { city: "Purchase", usaState: "New York", usaStateID: 33 },
  { city: "Stony Brook", usaState: "New York", usaStateID: 33 },
  { city: "Albany", usaState: "New York", usaStateID: 33 },
  { city: "Ft Leavenworth", usaState: "Kansas", usaStateID: 17 },
  { city: "Fort Leavenworth", usaState: "Kansas", usaStateID: 17 },
  { city: "Topeka", usaState: "Kansas", usaStateID: 17 },
  { city: "Leavenworth", usaState: "Kansas", usaStateID: 17 },
  { city: "Overland Park", usaState: "Kansas", usaStateID: 17 },
  { city: "Wichita", usaState: "Kansas", usaStateID: 17 },
  { city: "Olathe", usaState: "Kansas", usaStateID: 17 },
  { city: "Cedar Rapids", usaState: "Iowa", usaStateID: 16 },
  { city: "Des Moines", usaState: "Iowa", usaStateID: 16 },
  { city: "Coralville", usaState: "Iowa", usaStateID: 16 },
  { city: "Iowa City", usaState: "Iowa", usaStateID: 16 },
  { city: "West Des Moines", usaState: "Iowa", usaStateID: 16 },
  { city: "Bentonville", usaState: "Arkansas", usaStateID: 4 },
  { city: "Fayetteville", usaState: "Arkansas", usaStateID: 4 },
  { city: "Little Rock", usaState: "Arkansas", usaStateID: 4 },
  { city: "Lowell", usaState: "Arkansas", usaStateID: 4 },
  { city: "Baton Rouge", usaState: "Louisiana", usaStateID: 19 },
  { city: "Fort Polk", usaState: "Louisiana", usaStateID: 19 },
  { city: "New Orleans", usaState: "Louisiana", usaStateID: 19 },
  { city: "Pineville", usaState: "Louisiana", usaStateID: 19 },
  { city: "Hartford", usaState: "Connecticut", usaStateID: 7 },
  { city: "Norwalk", usaState: "Connecticut", usaStateID: 7 },
  { city: "Shelton", usaState: "Connecticut", usaStateID: 7 },
  { city: "Stamford", usaState: "Connecticut", usaStateID: 7 },
  { city: "Shelton", usaState: "Connecticut", usaStateID: 7 },
  { city: "Bloomfield", usaState: "Connecticut", usaStateID: 7 },
  { city: "Danbury", usaState: "Connecticut", usaStateID: 7 },
  { city: "Windsor Locks", usaState: "Connecticut", usaStateID: 7 },
  { city: "Greenwood Village", usaState: "Colorado", usaStateID: 6 },
  { city: "Pueblo", usaState: "Colorado", usaStateID: 6 },
  { city: "Colorado Springs", usaState: "Colorado", usaStateID: 6 },
  { city: "Peterson Air Force Base", usaState: "Colorado", usaStateID: 6 },
  { city: "Broomfield", usaState: "Colorado", usaStateID: 6 },
  { city: "Fort Collins", usaState: "Colorado", usaStateID: 6 },
  { city: "Lakewood", usaState: "Colorado", usaStateID: 6 },
  { city: "Denver", usaState: "Colorado", usaStateID: 6 },
  { city: "Golden", usaState: "Colorado", usaStateID: 6 },
  { city: "Centennial", usaState: "Colorado", usaStateID: 6 },
  { city: "Aspen", usaState: "Colorado", usaStateID: 6 },
  { city: "Boulder", usaState: "Colorado", usaStateID: 6 },
  { city: "Aurora", usaState: "Colorado", usaStateID: 6 },
  { city: "Englewood", usaState: "Colorado", usaStateID: 6 },
  { city: "Huntsville", usaState: "Alabama", usaStateID: 1 },
  { city: "Mobile", usaState: "Alabama", usaStateID: 1 },
  { city: "Tuskegee", usaState: "Alabama", usaStateID: 1 },
  { city: "Marshall Space Flight Center", usaState: "Alabama", usaStateID: 1 },
  { city: "Montgomery", usaState: "Alabama", usaStateID: 1 },
  { city: "Omaha", usaState: "Nebraska", usaStateID: 28 },
  { city: "Lafayette", usaState: "Louisiana", usaStateID: 19 },
  { city: "Shreveport", usaState: "Louisiana", usaStateID: 19 },
  { city: "Louisville", usaState: "Kentucky", usaStateID: 18 },
  { city: "Bowling Green", usaState: "Kentucky", usaStateID: 18 },
  { city: "Hill Air Force Base", usaState: "Utah", usaStateID: 46 },
  { city: "Salt Lake City", usaState: "Utah", usaStateID: 46 },
  { city: "Lindon", usaState: "Utah", usaStateID: 46 },
  { city: "Greenland", usaState: "New Hampshire", usaStateID: 30 },
  { city: "Madison", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Milwaukee", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Tomah", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Sun Prairie", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Pewaukee", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Honolulu", usaState: "Hawaii", usaStateID: 12 },
  { city: "Fort Shafter", usaState: "Hawaii", usaStateID: 12 },
  { city: "Indianapolis", usaState: "Indiana", usaStateID: 15 },
  { city: "Westfield", usaState: "Indiana", usaStateID: 15 },
  { city: "New Albany", usaState: "Indiana", usaStateID: 15 },
  { city: "Fort Wayne", usaState: "Indiana", usaStateID: 15 },
  { city: "Pine Ridge", usaState: "South Dakota", usaStateID: 43 },
  { city: "Sioux Falls", usaState: "South Dakota", usaStateID: 43 },
  { city: "Rapid City", usaState: "South Dakota", usaStateID: 43 },
  { city: "Vermillion", usaState: "South Dakota", usaStateID: 43 },
  { city: "Oklahoma City", usaState: "Oklahoma", usaStateID: 37 },
  { city: "Durant", usaState: "Oklahoma", usaStateID: 37 },
  { city: "Muskogee", usaState: "Oklahoma", usaStateID: 37 },
  { city: "Tulsa", usaState: "Oklahoma", usaStateID: 37 },
  { city: "Reno", usaState: "Nevada", usaStateID: 29 },
  { city: "Las Vegas", usaState: "Nevada", usaStateID: 29 },
  { city: "Sparks", usaState: "Nevada", usaStateID: 29 },
  { city: "Stennis Space Center", usaState: "Mississippi", usaStateID: 25 },
  { city: "Jackson", usaState: "Mississippi", usaStateID: 25 },
  { city: "Pleasant Prairie", usaState: "Wisconsin", usaStateID: 51 },
  { city: "Coeur d'Alene", usaState: "Idaho", usaStateID: 13 },
  { city: "Boise", usaState: "Idaho", usaStateID: 13 },
  { city: "San Juan", usaState: "Puerto Rico", usaStateID: 40 },
  { city: "Charleston", usaState: "South Carolina", usaStateID: 42 },
  { city: "Anderson", usaState: "South Carolina", usaStateID: 42 },
  { city: "Providence", usaState: "Rhode Island", usaStateID: 41 },
  { city: "Gaggio Montano", country: "Italy", countryID: 94 },
  { city: "Mumbai", country: "India", countryID: 87 },
  { city: "Madrid", country: "Spain", countryID: 180 },
  { city: "Barcelona", country: "Spain", countryID: 180 },
  { city: "Stockholm", country: "Sweden", countryID: 188 },
  { city: "Sao Paulo", country: "Brazil", countryID: 28 },
  { city: "Leamington Spa", country: "United Kingdom", countryID: 220 },
  { city: "Sydney", country: "Australia", countryID: 12 },
  { city: "North Ryde", country: "Australia", countryID: 12 },
  { city: "Brisbane", country: "Australia", countryID: 12 },
  { city: "Canberra", country: "Australia", countryID: 12 },
  { city: "Dublin", country: "Ireland", countryID: 91 },
  { city: "Toronto", country: "Canada", countryID: 37 },
  { city: "Saskatoon", country: "Canada", countryID: 37 },
  { city: "Eindhoven", country: "Netherlands", countryID: 140 },
  { city: "Pune", country: "India", countryID: 87 },
  { city: "Drachten", country: "Netherlands", countryID: 140 },
  { city: "Chennai", country: "India", countryID: 87 },
  { city: "Shoreham-by-Sea", country: "United Kingdom", countryID: 220 },
  { city: "Leeds", country: "United Kingdom", countryID: 220 },
  { city: "Shanghai", country: "China", countryID: 219 },
  { city: "Bangalore", country: "India", countryID: 87 },
  { city: "Hong Kong", country: "Hong Kong", countryID: 84 },
  { city: "Berlin", country: "Germany", countryID: 72 },
  { city: "Bonn", country: "Germany", countryID: 72 },
  { city: "Stuttgart", country: "Germany", countryID: 72 },
  { city: "Cologno Monzese", country: "Italy", countryID: 94 },
  { city: "Geneva", country: "Switzerland", countryID: 189 },
  { city: "Zurich", country: "Switzerland", countryID: 189 },
  { city: "Copenhagen", country: "Denmark", countryID: 53 },
  { city: "Beijing", country: "China", countryID: 219 },
  { city: "Milan", country: "Italy", countryID: 94 },
  { city: "Bengaluru", country: "India", countryID: 87 },
  { city: "Wuhan", country: "China", countryID: 219 },
  { city: "Amsterdam", country: "Netherlands", countryID: 140 },
  { city: "Edinburgh", country: "United Kingdom", countryID: 220 },
  { city: "Paris", country: "France", countryID: 66 },
  { city: "Clichy", country: "France", countryID: 66 },
  { city: "Boulogne", country: "France", countryID: 66 },
  { city: "Les Ulis Courtaboeuf", country: "France", countryID: 66 },
  { city: "Glasgow", country: "United Kingdom", countryID: 220 },
  { city: "Shenzhen", country: "China", countryID: 219 },
  { city: "Munich", country: "Germany", countryID: 72 },
  { city: "Best", country: "Netherlands", countryID: 140 },
  { city: "New Delhi", country: "India", countryID: 87 },
  { city: "Reading", country: "United Kingdom", countryID: 220 },
  { city: "Birmingham", country: "United Kingdom", countryID: 220 },
  { city: "Croydon", country: "United Kingdom", countryID: 220 },
  { city: "Boblingen", country: "Germany", countryID: 72 },
  { city: "Hayes Park", country: "United Kingdom", countryID: 220 },
  { city: "Hyderabad", country: "India", countryID: 87 },
  { city: "Coimbatore", country: "India", countryID: 87 },
  { city: "Winnersh", country: "United Kingdom", countryID: 220 },
  { city: "Manchester", country: "United Kingdom", countryID: 220 },
  { city: "Warrington", country: "United Kingdom", countryID: 220 },
  { city: "Slough", country: "United Kingdom", countryID: 220 },
  { city: "Milton Park", country: "United Kingdom", countryID: 220 },
  { city: "Peterborough", country: "United Kingdom", countryID: 220 },
  { city: "Wrexham", country: "United Kingdom", countryID: 220 },
  { city: "Gurugram", country: "India", countryID: 87 },
  { city: "Suzhou", country: "China", countryID: 219 },
  { city: "Montreal", country: "Canada", countryID: 37 },
  { city: "Vancouver", country: "Canada", countryID: 37 },
  { city: "Calgary", country: "Canada", countryID: 37 },
  { city: "Mississauga", country: "Canada", countryID: 37 },
  { city: "Burnaby", country: "Canada", countryID: 37 },
  { city: "Brussels", country: "Belgium", countryID: 20 },
  { city: "London", country: "United Kingdom", countryID: 220 },
  { city: "Bristol", country: "United Kingdom", countryID: 220 },
  { city: "Belfast", country: "United Kingdom", countryID: 220 },
  { city: "The Hague", country: "Netherlands", countryID: 140 },
  { city: "Luxembourg", country: "Luxembourg", countryID: 114 },
  { city: "Chennai", country: "India", countryID: 87 },
  { city: "Mexico City", country: "Mexico", countryID: 127 },
  { city: "Frankfurt", country: "Germany", countryID: 72 },
  { city: "Singapore", country: "Singapore", countryID: 174 },
  { city: "Dubai", country: "United Arab Emirates", countryID: 204 },
  { city: "Buenos Aires", country: "Argentina", countryID: 9 }
];

const functionKeywords = [
  {
    funKeywordArr: [
      "Accountant",
      "Tax",
      "Audit",
      "Auditor",
      "Controller",
      "Control",
      "Accounting"
    ],
    nameString: "Accounting / Control",
    idIvy: 0
  },
  {
    funKeywordArr: [
      "Proposal",
      "Capture",
      "Client",
      "Relationship",
      "Partnership",
      "Partnerships",
      "Philanthropy",
      "Growth"
    ],
    phrasesArr: [
      "Business Development",
      "Business Enablement",
      "Investor Relations",
    ],
    nameString: "Business Development",
    idIvy: 1
  },
  {
    funKeywordArr: ["Economic", "Economics"],
    nameString: "Economic Analysis",
    idIvy: 2
  },
  {
    funKeywordArr: [],
    nameString: "Entrepreneur / Owner",
    idIvy: 3
  },
  {
    funKeywordArr: ["Finance", "Budget", "Cost", "Revenue", "Reimbursement"],
    phrasesArr: [ "Financial Analyst", "Chief Financial Officer" ],
    nameString: "Finance (Internal)",
    idIvy: 4
  },
  {
    funKeywordArr: ["Bank", "Banking", "Insurance", "Credit", "Loan", "Wealth"],
    nameString: "Financial Services Professional",
    idIvy: 5
  },
  {
    funKeywordArr: ["Director", "Head", "Chief"],
    nameString: "General Management",
    idIvy: 6
  },
  {
    funKeywordArr: [
      "Benefits",
      "Recruiting",
      "Talent",
      "Recruiter",
      "Recruitment",
      "Generalist",
      "Employment",
      "Equal",
      "People",
      "Diversity",
      "Compensation",
      "Rewards"
    ],
    phrasesArr: [
      "Human Resources",
      "Learning And Development",
      "Learning & Development"
    ],
    nameString: "Human Resources",
    idIvy: 7
  },
  {
    funKeywordArr: [
      "Technology",
      "Architect",
      "Architecture",
      "IT",
      "Cyber",
      "Java",
      "Frontend",
      "Backend",
      "AWS",
      "Microsoft",
      "Azure",
      "Software",
      "Application",
      "Cybersecurity",
      "Cloud",
      "Solution",
      "Agile",
      "Bioinformatics",
    ],
    phrasesArr: [
      "Information Security",
      "Information Assurance",
      "Machine Learning",
      "Data Scientist",
      "Information Systems",
      "Data Science",
      "Scrum Master"
    ],
    nameString: "IT / Information Technology",
    idIvy: 8
  },
  {
    funKeywordArr: [
      "Marketing",
      "Insight",
      "Copywriter",
      "Campaign",
      "Commerce",
      "Advertising",
      "Pricing",
      "Brand",
      "Branding",
      "Market",
      "Gifts"
    ],
    phrasesArr: [
      "Product Management",
      "Product Manager",
      "Social Media",
      "Corporate Communications",
      "Internal Communications",
      "Customer Relationship Management"
    ],
    nameString: "Marketing",
    idIvy: 9
  },
  {
    funKeywordArr: ["Operations", "Production", "Manufacturing"],
    phrasesArr: [ "Food & Beverage" ],
    nameString: "Operations / Production",
    idIvy: 10
  },
  {
    funKeywordArr: [],
    nameString: "Other nameStringtions",
    idIvy: 11
  },
  {
    funKeywordArr: [],
    phrasesArr: ["Product Development"],
    nameString: "Product Development",
    idIvy: 12
  },
  {
    funKeywordArr: ["Real", "Estate"],
    phrasesArr: [ "Property Management" ],
    nameString: "Real Estate",
    idIvy: 13
  },
  {
    funKeywordArr: [],
    nameString: "Scientific Research",
    idIvy: 14
  },
  {
    funKeywordArr: [
      "Sales",
      "Account",
      "Store",
      "Accounts",
      "Retail",
      "Merchandising",
      "Commercial"
    ],
    nameString: "Sales",
    idIvy: 15
  },
  {
    funKeywordArr: ["Risk", "Casualty", "Modelling"],
    nameString: "Risk Management",
    idIvy: 16
  },
  {
    funKeywordArr: ["Regulatory"],
    nameString: "Regulatory Affairs",
    idIvy: 17
  },
  {
    funKeywordArr: ["President", "Strategy", "Strategic"],
    nameString: "Strategy",
    idIvy: 18
  },
  {
    funKeywordArr: [
      "Scientist",
      "Heliophysics",
      "Astrophysics",
      "Professor",
      "Postdoc",
      "Hospitalist",
      "Neuropsychologist",
      "Palliative",
      "Gastroenterologist",
      "Physicist",
      "Materials",
      "Postdoctoral",
      "Healthcare",
      "Health",
      "Research",
      "Biotech",
      "Researcher",
      "Physician",
      "Cardiologist",
      "Veterinarian",
      "Dentist",
      "Dental",
      "Nurse",
      "Nursing",
      "Psychologist",
      "Psychiatrist",
      "Epidemiologist",
      "Medical",
      "Medicine",
      "Pharmacist",
      "Pharmacy",
      "Pharmaceutical",
      "Psychiatry",
      "Biologist",
      "Chemist",
      "Chemistry",
      "Laboratory",
      "Therapy",
      "Dean",
      "Science",
      "Emergency",
      "Cardiac",
      "Ambulatory",
      "Anesthesiologist",
      "Anesthesiology",
      "Dermatologist",
      "Dermatology",
      "Radiologist",
      "Radiology",
      "Family",
      "Geneticist",
      "Geriatrics",
      "Obstetrician",
      "Obstetrics",
      "Neurologist",
      "Neurology",
      "Gynecologist",
      "Gynecology",
      "Ophthalmologist",
      "Pathologist",
      "Ophthalmology",
      "Pathology",
      "Pulmonologist",
      "Pediatrician",
      "Pediatrics",
      "Pediatric",
      "Rehabilitation",
      "Intensivist",
      "Otolaryngologist",
      "Rehab",
      "Brain",
      "Injury",
      "Oncology",
      "Oncologist",
      "Surgery",
      "Surgeon",
      "Inpatient",
      "Urology",
      "Urologist",
      "Psychology",
      "Patient",
      "Surgical",
      "Transplant",
      "Mathematician",
      "Astronomy",
      "Biostatistician",
      "Bioinformatics",
      "Mathematics",
      "Physics",
      "Biological",
      "Astrobiology",
      "Chemical",
      "Clinical",
      "Clinic",
      "Environmental",
      "Environment",
      "Geological",
      "Geology",
      "Geologist",
      "Physics",
      "Statistical",
      "Statistician",
      "Statistics",
      "Ecologist",
      "Ecology",
      "Sensing",
      "Ocean",
      "Physical",
      "Epidemiology"
    ],
    nameString: "Biotech/R&D/Science",
    idIvy: 19
  },
  {
    funKeywordArr: [
      "Engineering",
      "Engineer",
      "Aeronautic",
      "Agricultural",
      "Chemical",
      "Civil",
      "Structural",
      "Electrical",
      "Electronics",
      "Electronic",
      "Energy",
      "Nuclear",
      "Industrial",
      "Mechanical",
    ],
    nameString: "Engineering",
    idIvy: 20
  },
  {
    funKeywordArr: ["Board"],
    nameString: "Board Member",
    idIvy: 21
  },
  {
    funKeywordArr: [],
    nameString: "Consulting - Strategy",
    idIvy: 22
  },
  {
    funKeywordArr: [],
    nameString: "Consulting - IT",
    idIvy: 23
  },
  {
    funKeywordArr: [],
    nameString: "Consulting - Accounting",
    idIvy: 24
  },
  {
    funKeywordArr: ["Political"],
    nameString: "Consulting - Gov't / Non-Profit",
    idIvy: 25
  },
  {
    funKeywordArr: [
      "Project",
      "Projects",
      "Program",
      "Programs",
      "Programme",
      "Scheduler",
      "Schedule",
      "Earned",
      "Office"
    ],
    phrasesArr: [ "Task Manager" ],
    nameString: "Project Management",
    idIvy: 26
  },
  {
    funKeywordArr: ["Quality"],
    nameString: "Quality Assurance",
    idIvy: 27
  },
  {
    funKeywordArr: [
      "Purchasing",
      "Supply",
      "Chain",
      "Logistics",
      "Sourcing",
      "Transportation",
      "Procurement"
    ],
    nameString: "Purchasing / Supply Chain / Logistics",
    idIvy: 28
  },
  {
    funKeywordArr: [
      "Lawyer",
      "Legal",
      "Compliance",
      "Attorney",
      "Counsel",
      "Judge",
      "Contract",
      "Rights",
      "Contracts",
      "Subcontracts",
      "Subcontract",
      "Advocacy"
    ],
    nameString: "Legal / Compliance",
    idIvy: 29
  },
  {
    funKeywordArr: ["Administration", "Administrative"],
    nameString: "Administration",
    idIvy: 30
  },
  {
    funKeywordArr: [
      "Communications",
      "Outreach",
      "Communication",
    ],
    phrasesArr: [ "Public Relations" ],
    nameString: "PR & Communications",
    idIvy: 31
  },
  {
    funKeywordArr: ["Customer"],
    nameString: "Customer Experience & Support",
    idIvy: 32
  },
  {
    funKeywordArr: [
      "Art",
      "Graphic",
      "Design",
      "Designer",
      "Creative",
      "Graphics",
      "Graphic"
    ],
    nameString: "Design / Graphic Design",
    idIvy: 33
  },
  {
    funKeywordArr: ["Consulting", "Consultant", "Advisor", "Advisory"],
    nameString: "Consulting",
    idIvy: 9999
  }
];

const educationKeywords = [
  {
    eduKeywordsArr: [
      "Bachelor",      
      "Bachelor'S",
      "Bachelors",
      "Bachelors'",
      "Bachelor’S",
      "Bachelors’",
      "Bs",
      "Ba",
      "Bsc",
      "Undercityuate",
      "Bsee",
      "Bscs",
    ],
    phrasesArr: [ 
      "4 Year Degree",
      "Four Year Degree",
      "Post Secondary",
      "University Degree",
      "University cityuate",
      "Degree Educated",
      "College Degree",
      "B S",
      "B A",
      "4 Year College",
      "Four Year College",
      "College Level Education",
      "Cs Degree",
      "College cityuate"
    ],
    nameString: "Bachelor's Degree",
    idIvy: 14
  },
  {
    eduKeywordsArr: [ "Msn" ],
    phrasesArr: [ 
      // "Master Degree",
      // "Masters Degree",
      // "Master'S Degree",
      // "Master’S Degree",
      "Master Student",
      "cityuate Student",
      "cityuate Degree",
      "Advanced Degree",
      "Advanced University Degree",
    ],
    nameString: "Other Masters",
    idIvy: 6
  },
  {
    eduKeywordsArr: [
      "Postcityuate",
      "Doctoral",
      "Doctorate",
      "Phd",     
    ],
    phrasesArr: [ "Post cityuate", "Ph D", "Terminal Degree" ],
    nameString: "PhD",
    idIvy: 5
  },
  {
    eduKeywordsArr: [ "Dvm", "Pharmd", "Dmd" ],
    phrasesArr: [ 
      "Pharm D",
      "Psy D",
      "Doctor Of Dental Medicine"
    ],
    nameString: "Other Doctoral",
    idIvy: 7
  },
  {
    eduKeywordsArr: [ "Md" ],
    phrasesArr: [ 
      "Physician License",
      "Medical Degree",
      "M D",
      "Doctor Of Medicine",
      "Medical License",
      "License To Practice Medicine",
      "Board Certified",
      "Board Certification"
     ],
    nameString: "Doctor of Medicine",
    idIvy: 4
  },
  {
    eduKeywordsArr: [ "Mba" ],
    phrasesArr: [ 
      "Master Of Business Administration",
      "Masters Of Business Administration",
      "Masters In Business Administration",
      "Master In Business Administration",
      "Master’S Degree In Business Administration"
     ],
    nameString: "Master of Business Administration",
    idIvy: 0
  },
  {
    eduKeywordsArr: ["Juris", "Jd", ],
    phrasesArr: [ "Juris Doctor", "J D", "Doctor Of Jurisprudence" ],
    nameString: "Juris Doctor",
    idIvy: 3
  },
  {
    eduKeywordsArr: [ "Llm" ],
    phrasesArr: [ 
      "Ll M",
      "Master Of Law",
      "Masters Of Law"
     ],
    nameString: "Master of Laws (LL.M.)",
    idIvy: 30
  },
  {
    eduKeywordsArr: [ "Msit" ],
    phrasesArr: [ 
      "Masters Degree In Information Technology",
      "Master Degree In Information Technology",
      "Master Of Science In Information Technology",
      "Master'S Degree In Information Technology"
     ],
    nameString: "Master of Science in Information Technology (MSIT)",
    idIvy: 27
  },
  {
    eduKeywordsArr: ["Msee", "Ms", "Msc", ],
    phrasesArr: [ "M S" ],
    nameString: "Master of Science",
    idIvy: 11
  },
  {
    eduKeywordsArr: [ ],
    phrasesArr: [ "Master Degree In Management" ],
    nameString: "Master of Management (MAM)",
    idIvy: 18
  },
  {
    eduKeywordsArr: [ "Mcs" ],
    phrasesArr: [ 
      "Master Of Computer Science",
      "Masters Of Computer Science",
      "Master Degree In Computer Science",
      "Masters Degree In Computer Science",
      "Master’S Degree In Computer Science",
      "Ms In Computer Science"
     ],
    nameString: "Master of Computer Science (MCS)",
    idIvy: 28
  },
  {
    eduKeywordsArr: [ "Mha", ],
    phrasesArr: [ 
      "Master Of Health Administration",
      "Masters Of Health Administration"
    ],
    nameString: "Master of Health Administration (MHA)",
    idIvy: 16
  },
  {
    eduKeywordsArr: [ ],
    phrasesArr: [ 
    "Master’S In Finance",
    "Master In Finance",
    "Masters In Finance",
    "Master'S In Finance",
    "Master Of Science in Finance",
    "Masters Of Science in Finance",
    "Master’S Of Science in Finance",
    "Master'S Of Science in Finance",
    "Master’S Degree In Finance",
    "Master'S Degree In Finance",
    "Master Degree In Finance",
    "Masters Degree In Finance"
   ],
    nameString: "Master of Science in Finance (MSF)",
    idIvy: 21
  },
  {
    eduKeywordsArr: [ "Mph" ],
    phrasesArr: [ "Master Of Public Health",
                "Masters Of Public Health",
                "Master’S Of Public Health"
    ],
    nameString: "Master of Public Health (MPH)",
    idIvy: 15
  },
  {
    eduKeywordsArr: [ ],
    phrasesArr: [ "Master'S Degree In Accounting", "Masters Degree in Accounting", "Master Degree In Accounting", "Master’S Degree in Accounting"],
    nameString: "Master of Accountancy (MAcy)",
    idIvy: 19
  },
  {
    eduKeywordsArr: ["Mfa", "Ma"],
    phrasesArr: [ "Master Of Arts", ],
    nameString: "Master of Arts",
    idIvy: 10
  },
  {
    eduKeywordsArr: [ ],
    phrasesArr: [ "Masters Degree In Technology", "Master of Technology", "M Tech" ],
    nameString: "Master of Technology (M.Tech.)",
    idIvy: 26
  }
];

const specialtyKeywords = [
  {
    specialtyKeywordsArr: [ ],
    phrasesArr: [ "Property Management" ],
    nameString: "Property Management",
    idIvy: 86
  },
  {
    specialtyKeywordsArr: ["Mechanical"],
    nameString: "Mechanical Engineering",
    idIvy: 106
  },
  {
    specialtyKeywordsArr: ["Process", "Processes"],
    phrasesArr: [ "System Engineer", "Systems Engineer" ],
    nameString: "Systems/Process Engineering",
    idIvy: 109
  },
  {
    specialtyKeywordsArr: ["Electrical", "Electronics", "Microelectronics"],
    nameString: "Electrical/Electronics Engineering",
    idIvy: 101
  },
  {
    specialtyKeywordsArr: ["Aerospace", "Aeronautical"],
    nameString: "Aeronautic/Avionic Engineering",
    idIvy: 97
  },
  {
    specialtyKeywordsArr: ["Rf", "Wireless"],
    nameString: "RF/Wireless Engineering",
    idIvy: 108
  }, // 
  {
    specialtyKeywordsArr: ["Tax"],
    nameString: "Tax Accounting",
    idIvy: 35
  },
  {
    specialtyKeywordsArr: ["Audit", "Auditor"],
    nameString: "Auditing",
    idIvy: 33
  },
  {
    specialtyKeywordsArr: ["Pricing"],
    nameString: "Pricing",
    idIvy: 20
  },
  {
    specialtyKeywordsArr: ["Brand", ],
    phrasesArr: [
       "Product Management",
       "Product Manager",
       "Product Marketing",
    ],
    nameString: "Brand/Product Management",
    idIvy: 17
  },
  {
    specialtyKeywordsArr: [],
    phrasesArr: [ "Corporate Communications" ],
    nameString: "Corporate communications",
    idIvy: 32
  },
  {
    specialtyKeywordsArr: ["Advertising", ],
    nameString: "Advertising",
    idIvy: 81
  },
  {
    specialtyKeywordsArr: [
      "Clinical",
      "Clinic",
      "Hospitalist",
      "Neuropsychologist",
      "Palliative",
      "Gastroenterologist",
      "Healthcare",
      "Health",
      "Physician",
      "Cardiologist",
      "Veterinarian",
      "Dentist",
      "Dental",
      "Nurse",
      "Nursing",
      "Psychologist",
      "Psychiatrist",
      "Medical",
      "Medicine",
      "Pharmacist",
      "Pharmacy",
      "Pharmaceutical",
      "Psychiatry",
      "Emergency",
      "Cardiac",
      "Ambulatory",
      "Anesthesiologist",
      "Anesthesiology",
      "Dermatologist",
      "Dermatology",
      "Radiologist",
      "Radiology",
      "Family",
      "Geneticist",
      "Geriatrics",
      "Obstetrician",
      "Obstetrics",
      "Neurologist",
      "Neurology",
      "Gynecologist",
      "Gynecology",
      "Ophthalmologist",
      "Pathologist",
      "Ophthalmology",
      "Pathology",
      "Pediatrician",
      "Pediatrics",
      "Pediatric",
      "Rehabilitation",
      "Rehab",
      "Brain",
      "Injury",
      "Oncology",
      "Oncologist",
      "Surgery",
      "Surgeon",
      "Inpatient",
      "Urology",
      "Urologist",
      "Psychology",
      "Patient",
      "Surgical",
      "Transplant",
      "Therapy",
      "Epidemiology",
      "Epidemiologist"
    ],
    nameString: "General/Other: R&D/Science",
    idIvy: 92
  },
  {
    specialtyKeywordsArr: ["Physicist", "Physics", "Material", "Astronomy", "Materials", "Physical", "Astrophysics", "Heliophysics"],
    nameString: "Materials/Physical Research",
    idIvy: 93
  },
  {
    specialtyKeywordsArr: [
      "Biologist",
      "Chemist",
      "Biological",
      "Chemical",
      "Biology",
      "Chemistry",
      "Biostatistician",
      "Astrobiology",
      "Bioinformatics",
    ],
    nameString: "Biological/Chemical Research",
    idIvy: 89
  },
  {
    specialtyKeywordsArr: [
      "Environmental",
      "Environment",
      "Geological",
      "Geology",
      "Geologist",
      "Ecologist",
      "Ecology",
      "Ocean"
    ],
    phrasesArr: [ "Earth Science", "Remote Sensing" ],
    nameString: "Environmental/Geological Testing & Analysis",
    idIvy: 91
  },
  {
    specialtyKeywordsArr: [
        "Mathematician",
        "Mathematics",           
        "Statistical",
        "Statistician",
        "Statistics",
        "Biostatistician"
    ],
    phrasesArr: [ "Data Science", "Data Scientist" ],
    nameString: "Mathematical/Statistical Research",
    idIvy: 94
  },
  {
    specialtyKeywordsArr: [ ],
    phrasesArr: [ 
      "Digital Marketing",
      "Social Media",
    ],
    nameString: "Web Marketing",
    idIvy: 26
  }
];

const experienceDataArray =  [
  {
    idIvy: "0",
    nameString: "1-3",
    floor: 1,
    ceiling: 3
  },
  {
    idIvy: "1",
    nameString: "3-5",
    floor: 3,
    ceiling: 5
  },
  {
    idIvy: "2",
    nameString: "5-7",
    floor: 5,
    ceiling: 7
  },
  {
    idIvy: "3",
    nameString: "7-10",
    floor: 7,
    ceiling: 10
  },
  {
    idIvy: "4",
    nameString: "10-12",
    floor: 10,
    ceiling: 12
  },
  {
    idIvy: "5",
    nameString: "12-15",
    floor: 12,
    ceiling: 15
  },
  {
    idIvy: "6",
    nameString: "15-20",
    floor: 15,
    ceiling: 20
  },
  {
    idIvy: "7",
    nameString: "20+",
    floor: 20,
    ceiling: 99
  },
];

const additionalEducation = [
  {
     phrasesArr: [ 
      "Healthcare Administration",
      "Health Administration"
     ],
     nameString: "Master of Health Administration (MHA)",
     idIvy: 16
  },
  {
     phrasesArr: [ 
      "Management",
     ],
     nameString: "Master of Management (MAM)",
     idIvy: 18
  },
  {
    phrasesArr: [ 
      "Marketing",
      "Statistics",
      "Nursing",
      "Communications"
     ],
     nameString: "Other Masters",
     idIvy: 6
  },
  {
    phrasesArr: [ 
      "MSF",
      "Finance"
     ],
     nameString: "Master of Science in Finance (MSF)",
     idIvy: 21
  },
  {
    phrasesArr: [ 
      "Accounting"
     ],
     nameString: "Master of Accountancy (MAcy)",
     idIvy: 19
  },
  {
    phrasesArr: [ 
      "Engineering",
      "Material Science",
      "Chemistry",
      "Bicrobiology",
      "Biology",
      "Psychology",
      "Physics"
     ],
     nameString: "Master of Science",
     idIvy: 11
  },
  {
    phrasesArr: [ 
      "Computer"
     ],
     nameString: "Master of Computer Science (MCS)",
     idIvy: 28
  },
  {
    phrasesArr: [ 
      "Business Administration",
     ],
     nameString: "Master of Business Administration",
     idIvy: 0
  },
  {
    phrasesArr: [ 
      "Information Systems",
     ],
     nameString: "Master of Science in Information Systems (MSIS)",
     idIvy: 29
  },
  {
    phrasesArr: [ 
      "Information Technology",
     ],
     nameString: "Master of Science in Information Technology (MSIT)",
     idIvy: 27
  },
  {
    phrasesArr: [ 
      "Public Administration",
     ],
     nameString: "Master of Public Administration",
     idIvy: 2
  },
  {
    phrasesArr: [ 
      "Public Health",
     ],
     nameString: "Master of Public Health (MPH)",
     idIvy: 15
  },
  {
    phrasesArr: [ 
      "Public Policy",
     ],
     nameString: "Master of Public Policy",
     idIvy: 9
  },
  {
    phrasesArr: [ 
      "Architecture",
     ],
     nameString: "Master of Architecture (M.Arch.)",
     idIvy: 24
  },
  {
    phrasesArr: [ 
      "Tax",
     ],
     nameString: "Master of Science in Taxation (MST)",
     idIvy: 20
  },
  {
    phrasesArr: [ 
      "International Affairs",
      "International Relations"
     ],
     nameString: "Master of International Affairs",
     idIvy: 1
  },
];